# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ui_thread.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Thread(object):
    def setupUi(self, Thread):
        Thread.setObjectName("Thread")
        Thread.resize(212, 40)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Thread.sizePolicy().hasHeightForWidth())
        Thread.setSizePolicy(sizePolicy)
        Thread.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton = QtWidgets.QPushButton(Thread)
        self.pushButton.setGeometry(QtCore.QRect(130, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Thread)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 113, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Thread)
        QtCore.QMetaObject.connectSlotsByName(Thread)

    def retranslateUi(self, Thread):
        _translate = QtCore.QCoreApplication.translate
        Thread.setWindowTitle(_translate("Thread", "Form"))
        self.pushButton.setText(_translate("Thread", "PushButton"))
